### PR TITLE
added EFL (2019-2020)

### PR DESCRIPTION
**Pull request by kivanccakmak**

### CODE REVIEW

**Comment by geraldb** [comment]
Thanks again for helping out and the EFL update. Keep it up. Stay home. Wash hands (with soap). Stay healthy. Cheers.

**Comment by geraldb** [comment]
@kivanccakmak You're welcome to join the football team / org here on github so can edit in-place without pull request.  Just let me know if you're interested and I send you an invitation (via GitHub) per email. Cheers. Prost.

**Comment by kivanccakmak** [comment]
> @kivanccakmak You're welcome to join the football team / org here on github so can edit in-place without pull request. Just let me know if you're interested and I send you an invitation (via GitHub) per email. Cheers. Prost.



> Thanks again for helping out and the EFL update. Keep it up. Stay home. Wash hands (with soap). Stay healthy. Cheers.

thanks! I'm doing all and recommend you some of my other practices: ventilate frequently, have vitamin C (mostly by green pepper and orange) and D. take care!

**Comment by kivanccakmak** [comment]
> @kivanccakmak You're welcome to join the football team / org here on github so can edit in-place without pull request. Just let me know if you're interested and I send you an invitation (via GitHub) per email. Cheers. Prost.

@geraldb I would like to..

**Comment by geraldb** [comment]
First, thanks for the extra stay healthy tips.  //   Welcome.  Note: You will get an invitation (by email from GitHub) to join the openfootball org as a member or if I can remember the inivitation should also show-up on github itself on your home page. If you accept, you can update the football.json pages with write access directly - no longer any need for a pull request  and you will show up in the people page too (if you set your preference to public - default is private; change the setting in the [github org people page](https://github.com/orgs/openfootball/people)). Cheers. Prost.

**Pull request merged**
